### ISSUE TITLE
Crashes Minecraft when clicked on (v3.1.0)

### ISSUE THREAD

**Issue by Nijoma69** [Tfarcenim/crafting-station#52]
Hi,

I have just updated a few mods in my Minecraft instance (one of them being Crafting Station). Mincraft now crashes whenever I click on the crafting station, as per what another user on CurseForge has commented my Crafting Station is next to an inventory item (Chest). My crashlog is as follows (full log attached): -

Time: 07/04/20 21:07
Description: Exception in server tick loop

java.lang.NoClassDefFoundError: tfar/extratags/api/tagtypes/BlockEntityTypeTags
	at com.tfar.craftingstation.Configs.<clinit>(Configs.java:12) ~[?:3.1.0] {re:classloading}
	at com.tfar.craftingstation.CraftingStationContainer.<init>(CraftingStationContainer.java:82) ~[?:3.1.0] {re:classloading}
	at com.tfar.craftingstation.CraftingStationBlockEntity.createMenu(CraftingStationBlockEntity.java:59) ~[?:3.1.0] {re:classloading}
	at net.minecraftforge.fml.network.NetworkHooks.openGui(NetworkHooks.java:206) ~[?:?] {re:classloading}
	at net.minecraftforge.fml.network.NetworkHooks.openGui(NetworkHooks.java:172) ~[?:?] {re:classloading}
	at com.tfar.craftingstation.CraftingStationBlock.func_225533_a_(CraftingStationBlock.java:66) ~[?:3.1.0] {re:classloading}
	at net.minecraft.block.BlockState.func_227031_a_(BlockState.java:269) ~[?:?] {re:mixin,re:classloading}
	at net.minecraft.server.management.PlayerInteractionManager.func_219441_a(PlayerInteractionManager.java:334) ~[?:?] {re:classloading}
	at net.minecraft.network.play.ServerPlayNetHandler.func_184337_a(ServerPlayNetHandler.java:853) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.network.play.client.CPlayerTryUseItemOnBlockPacket.func_148833_a(SourceFile:36) ~[?:?] {re:classloading}
	at net.minecraft.network.play.client.CPlayerTryUseItemOnBlockPacket.func_148833_a(SourceFile:10) ~[?:?] {re:classloading}
	at net.minecraft.network.PacketThreadUtil.func_225383_a(SourceFile:21) ~[?:?] {re:classloading}
	at net.minecraft.util.concurrent.TickDelayedTask.run(SourceFile:18) ~[?:?] {re:classloading}
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(SourceFile:144) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23) ~[?:?] {re:classloading}
	at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:731) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:141) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(SourceFile:118) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_213205_aW(MinecraftServer.java:714) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_213168_p(MinecraftServer.java:708) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213161_c(SourceFile:127) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_213202_o(MinecraftServer.java:694) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:641) [?:?] {re:classloading,pl:accesstransformer:B}
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_192] {}
Caused by: java.lang.ClassNotFoundException: tfar.extratags.api.tagtypes.BlockEntityTypeTags
	at java.lang.ClassLoader.findClass(Unknown Source) ~[?:1.8.0_192] {}
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_192] {}
	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:101) ~[modlauncher-5.0.0-milestone.4.jar:?] {re:classloading}
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_192] {}
	... 24 more

[crash-2020-04-07_21.07.40-server.txt](https://github.com/Tfarcenim/crafting-station/files/4446842/crash-2020-04-07_21.07.40-server.txt)

**Comment by Tfarcenim** [comment]
missing required dependency https://www.curseforge.com/minecraft/mc-mods/extra-tags
I am puzzled how it even continued loading given this https://github.com/Tfarcenim/crafting-station/blob/1.15.x/src/main/resources/META-INF/mods.toml#L43

**Comment by Nijoma69** [comment]
OK my bad ...

I completely missed that 3.1.0 now requires ExtraTags (just re-read the crashlog)

Also ...

Minecraft isn't announcing that a required dependency is missing during mod loading / startup even though you have it declared in the mods.toml file.
