### ISSUE TITLE
Crash when putting items into a BDSandM Shipping Crate

### ISSUE THREAD

**Issue by twothe** [Tfarcenim/crafting-station#56]
I placed a Crafting Table next to a Shipping Crate, took out a stack of items and placed it back into an empty slot. That crashed the game.

Additionally it is not possible to put the item back into the slot it came from, because that slot has more than 64 items and therefore is considered to be full, while it can actually hold several thousand items.

```
java.lang.ClassCastException: funwayguy.bdsandm.inventory.capability.ShippingProxyWrapper cannot be cast to net.minecraftforge.items.IItemHandlerModifiable
	at net.minecraftforge.items.SlotItemHandler.func_75215_d(SlotItemHandler.java:80)
	at com.tfar.craftingstation.slot.WrapperSlot.func_75215_d(WrapperSlot.java:44)
	at net.minecraft.inventory.Container.func_184996_a(Container.java:281)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_187098_a(PlayerControllerMP.java:566)
	at net.minecraft.client.gui.inventory.GuiContainer.func_184098_a(GuiContainer.java:638)
	at net.minecraft.client.gui.inventory.GuiContainer.func_146286_b(GuiContainer.java:604)
	at com.tfar.craftingstation.client.CraftingStationScreen.func_146286_b(CraftingStationScreen.java:169)
	at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:543)
	at com.tfar.craftingstation.client.CraftingStationScreen.func_146274_d(CraftingStationScreen.java:146)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:501)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1759)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1098)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
```

Minecraft: 12.2
Crafting Station: 0.1.7b
BDSandM: 0.0.24
Forge: 2854

**Comment by Tfarcenim** [comment]
big stacks and mc don't mix, anyways it will no longer be possible to access from the table
