### ISSUE TITLE
Server crashes when I try to join

### ISSUE THREAD

**Issue by Aarwen1969** [Tfarcenim/crafting-station#64]
I really would love to have this mod working so I'm actually submitting my first bug report. Thank you for making mods.

It's a private 1.16 forge server on my personal computer.  I haven't written code since apple basic so I'm clueless but here is my crash report and the latest log text.

---- Minecraft Crash Report ----
// My bad.

Time: 8/4/20 12:02 AM
Description: Exception in server tick loop

java.lang.NoSuchMethodError: net.minecraft.tags.TagRegistry.func_232932_a_()V
	at tfar.extratags.api.ModTag.markReady(ModTag.java:27) ~[?:2.1e] {re:classloading}
	at java.util.ArrayList.forEach(Unknown Source) ~[?:1.8.0_251] {}
	at tfar.extratags.ExtraTags.onPlayerLogin(ExtraTags.java:49) ~[?:2.1e] {re:classloading,re:mixin}
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:212) ~[eventbus-2.2.0-service.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:204) ~[eventbus-2.2.0-service.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258) ~[eventbus-2.2.0-service.jar:?] {}
	at net.minecraftforge.fml.hooks.BasicEventHooks.firePlayerLoggedIn(BasicEventHooks.java:44) ~[?:?] {re:classloading}
	at net.minecraft.server.management.PlayerList.func_72355_a(PlayerList.java:227) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.network.login.ServerLoginNetHandler.func_147326_c(ServerLoginNetHandler.java:116) ~[?:?] {re:classloading}
	at net.minecraft.network.login.ServerLoginNetHandler.func_73660_a(ServerLoginNetHandler.java:63) ~[?:?] {re:classloading}
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:222) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:133) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:866) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:286) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:788) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:643) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.lambda$func_240784_a_$0(MinecraftServer.java:230) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_251] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.16.1
	Minecraft Version ID: 1.16.1
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_251, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 2792327152 bytes (2662 MB) / 4206886912 bytes (4012 MB) up to 4206886912 bytes (4012 MB)
	CPUs: 4
	JVM Flags: 2 total; -Xmx4096M -Xms4096M
	ModLauncher: 5.1.0+69+master.79f13f7
	ModLauncher launch target: fmlserver
	ModLauncher naming: srg
	ModLauncher services: 
		/mixin-0.8.jar mixin PLUGINSERVICE 
		/eventbus-2.2.0-service.jar eventbus PLUGINSERVICE 
		/forgeserver.jar object_holder_definalize PLUGINSERVICE 
		/forgeserver.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-2.1.3-shadowed.jar accesstransformer PLUGINSERVICE 
		/forgeserver.jar capability_inject_definalize PLUGINSERVICE 
		/forgeserver.jar runtimedistcleaner PLUGINSERVICE 
		/mixin-0.8.jar mixin TRANSFORMATIONSERVICE 
		/OptiFine_1.16.1_HD_U_G2.jar OptiFine TRANSFORMATIONSERVICE 
		/forgeserver.jar fml TRANSFORMATIONSERVICE 
	FML: 32.0
	Forge: net.minecraftforge:32.0.75
	FML Language Providers: 
		javafml@32.0
		minecraft@1
	Mod List: 
		forge-1.16.1-32.0.75-server.jar Minecraft {minecraft@1.16.1 DONE}
		lightestlamp-4.0.2.jar Lightest Lamps {lightestlamp@4.0.2 DONE}
		doubledoors_1.16-2.1.jar Double Doors {doubledoors@2.1 DONE}
		theoneprobe-1.16-3.0.1-beta.jar The One Probe {theoneprobe@1.16-3.0.1-beta DONE}
		MouseTweaks-2.13-mc1.16.1.jar Mouse Tweaks {mousetweaks@2.13 DONE}
		ToolBelt-1.16.1-1.14.2.jar Tool Belt {toolbelt@1.14.2 DONE}
		SilentLib-1.16.1-4.7.0+58.jar Silent Lib {silentlib@4.7.0+58 DONE}
		BiomesOPlenty-1.16.1-11.0.0.390-universal.jar Biomes O' Plenty {biomesoplenty@1.16.1-11.0.0.390 DONE}
		mining-helmet-1.16.1-1.0.8.jar Mining Helmet {mining_helmet@1.0.8 DONE}
		craftingstation-4.0.0a.jar Crafting Station {craftingstation@4.0.0a DONE}
		harvestsprites-1.16.1-1.1.0.jar Harvest Sprites {harvestsprites@1.16.1-1.1.0 DONE}
		jei-1.16.1-7.0.0.6.jar Just Enough Items {jei@7.0.0.6 DONE}
		packedup-1.0.15-mc1.16.jar PackedUp {packedup@1.0.15 DONE}
		Mekanism-1.16.1-10.0.3.426.jar Mekanism {mekanism@10.0.3 DONE}
		SilentMechanisms-1.16.1-0.8.1+62.jar Silent's Mechanisms {silents_mechanisms@0.8.1+62 DONE}
		reap-1.16.1-1.0.3.jar Reap Mod {reap@1.16.1-1.0.3 DONE}
		sleeping_bags-1.16.1-1.0.2.jar Sleeping Bags {sleeping_bags@1.16.1-1.0.2 DONE}
		invtweaks-1.16.1-1.0.5.jar Inventory Tweaks Renewed {invtweaks@1.16.1-1.0.5 DONE}
		rndbmflowers_1.16-1.2.jar Random Bone Meal Flowers {rndbmflowers@1.2 DONE}
		gravestone-1.16.1-1.0.3.jar Gravestone Mod {gravestone@1.16.1-1.0.3 DONE}
		collective-1.16.1-1.35.jar Collective {collective@1.35 DONE}
		OverpoweredMending-1.16.1-2.0.0+11.jar Overpowered Mending {overpowered_mending@2.0.0+11 DONE}
		extratags-2.1e.jar Extra Tags {extratags@2.1e DONE}
		sweetconcrete-1.16.1-1.7.1.jar Sweet Concrete {sweetconcrete@1.16.1-1.7.1 DONE}
		NaturesCompass-1.16.1-1.8.5.jar Nature's Compass {naturescompass@1.16.1-1.8.5 DONE}
		DoubleSlabs-1.16-3.2.0.jar Double Slabs {doubleslabs@3.2.0 DONE}
		backpacked-1.4.4-1.16.1.jar Backpacked {backpacked@1.4.4 DONE}
		FarmingForBlockheads_1.16.1-7.0.1.jar Farming for Blockheads {farmingforblockheads@7.0.1 DONE}
		Actually+Useful+Stonecutter-1.0.1+mc+1.16.1.jar Actually Useful Stonecutter {actuallyusefulstonecutter@1.0.1 mc 1.16.1 DONE}
		bedspreads-FORGE-1.16.1-4.0.0.1.jar Bedspreads {bedspreads@FORGE-1.16.1-4.0.0.1 DONE}
		travellersboots-1.16.1-1.4.0.jar Traveller's Boots {travellersboots@1.4.0 DONE}
		globalxp-1.16.1-v1.4.13.jar Global XP {globalxp@v1.4.13 DONE}
		MekanismGenerators-1.16.1-10.0.3.426.jar Mekanism: Generators {mekanismgenerators@10.0.3 DONE}
		PackingTape-1.16.1-0.9.6.jar Packing Tape {packingtape@0.9.6 DONE}
		kelpfertilizer_1.16-1.1.jar Kelp Fertilizer {kelpfertilizer@1.1 DONE}
		forgemod_VoxelMap-1.10.6b_for_1.16.1.jar VoxelMap {voxelmap@1.10.6 DONE}
		woodcutter-1.1-1.16.1.jar Wood Cutter {woodcutter@1.1-1.16.1 DONE}
		getinthebucketmod-1.16.1-3.0.0-beta.jar Get In The Bucket Mod {getinthebucketmod@3.0.0-beta DONE}
		extendedbonemeal_1.16-1.1.jar Extended Bone Meal {extendedbonemeal@1.1 DONE}
		forge-1.16.1-32.0.75-universal.jar Forge {forge@32.0.75 DONE}
		infinitetrading_1.16-1.1.jar Infinite Trading {infinitetrading@1.1 DONE}
		FastLeafDecay-v23.jar FastLeafDecay {fastleafdecay@v23 DONE}
		refinedstorage-1.9.2.jar Refined Storage {refinedstorage@1.9.2 DONE}
		refinedstorageaddons-0.7.jar Refined Storage Addons {refinedstorageaddons@0.7 DONE}
		QuantumStorage-1.16.1-5.2.0.jar QuantumStorage {quantumstorage@NONE DONE}
		supertools-1.16.1-2.jar Vanilla+ Tools {supertools@version DONE}
	Player Count: 1 / 20; [ServerPlayerEntity['Arwen1969'/37, l='ServerLevel[world]', x=-987.37, y=78.00, z=-1291.35]]
	Data Packs: vanilla, mod:lightestlamp, mod:doubledoors, mod:mousetweaks (incompatible), mod:toolbelt (incompatible), mod:biomesoplenty, mod:mining_helmet (incompatible), mod:harvestsprites, mod:jei (incompatible), mod:mekanism, mod:reap, mod:sleeping_bags, mod:invtweaks (incompatible), mod:rndbmflowers, mod:gravestone, mod:collective, mod:naturescompass (incompatible), mod:doubleslabs, mod:backpacked, mod:farmingforblockheads (incompatible), mod:travellersboots (incompatible), mod:mekanismgenerators, mod:packingtape, mod:kelpfertilizer, mod:voxelmap, mod:getinthebucketmod (incompatible), mod:extendedbonemeal, mod:forge, mod:infinitetrading, mod:fastleafdecay, mod:refinedstorage, mod:refinedstorageaddons, mod:quantumstorage (incompatible), mod:supertools (incompatible), mod:packedup, mod:silentlib (incompatible), mod:silents_mechanisms (incompatible), mod:overpowered_mending (incompatible), mod:globalxp, mod:woodcutter (incompatible), mod:theoneprobe (incompatible), mod:craftingstation (incompatible), mod:extratags (incompatible), mod:sweetconcrete (incompatible), mod:actuallyusefulstonecutter (incompatible), mod:bedspreads (incompatible)
	Is Modded: Definitely; Server brand changed to 'forge'
	Type: Dedicated Server (map_server.txt)

LATEST LOG:

[04Aug2020 00:00:02.694] [User Authenticator #2/INFO] [net.minecraft.network.login.ServerLoginNetHandler/]: UUID of player Arwen1969 is 93b9b770-ae19-4878-88c2-1c301e04cef6
[04Aug2020 00:00:02.785] [Netty Server IO #2/ERROR] [net.minecraftforge.fml.network.NetworkRegistry/NETREGISTRY]: Channels [lightestlamp:main] rejected their client side version number
[04Aug2020 00:00:02.785] [Netty Server IO #2/ERROR] [net.minecraftforge.fml.network.FMLHandshakeHandler/FMLHANDSHAKE]: Terminating connection with client, mismatched mod list
[04Aug2020 00:00:02.824] [Server thread/INFO] [net.minecraft.network.login.ServerLoginNetHandler/]: com.mojang.authlib.GameProfile@6832a287[id=93b9b770-ae19-4878-88c2-1c301e04cef6,name=Arwen1969,properties={textures=[com.mojang.authlib.properties.Property@1faeb0d]},legacy=false] (/10.0.0.167:50446) lost connection: Connection closed - mismatched mod channel list
[04Aug2020 00:02:43.825] [User Authenticator #3/INFO] [net.minecraft.network.login.ServerLoginNetHandler/]: UUID of player Arwen1969 is 93b9b770-ae19-4878-88c2-1c301e04cef6
[04Aug2020 00:02:45.946] [Server thread/INFO] [net.minecraftforge.common.AdvancementLoadFix/]: Using new advancement loading for net.minecraft.advancements.PlayerAdvancements@8f3874e
[04Aug2020 00:02:45.981] [Server thread/INFO] [net.minecraft.server.management.PlayerList/]: Arwen1969[/10.0.0.167:50499] logged in with entity id 37 at (-987.3709477681646, 78.0, -1291.3464108354754)
[04Aug2020 00:02:46.053] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer/]: Arwen1969 joined the game
[04Aug2020 00:02:46.069] [Netty Server IO #3/ERROR] [net.minecraft.command.arguments.ArgumentTypes/]: Could not serialize net.minecraftforge.server.command.ModIdArgument@5985d602 (class net.minecraftforge.server.command.ModIdArgument) - will not be sent to client!
[04Aug2020 00:02:46.072] [Netty Server IO #3/ERROR] [net.minecraft.command.arguments.ArgumentTypes/]: Could not serialize net.minecraftforge.server.command.EnumArgument@4a41d671 (class net.minecraftforge.server.command.EnumArgument) - will not be sent to client!
[04Aug2020 00:02:46.092] [Server thread/ERROR] [net.minecraftforge.eventbus.EventBus/EVENTBUS]: Exception caught during firing event: net.minecraft.tags.TagRegistry.func_232932_a_()V
	Index: 5
	Listeners:
		0: NORMAL
		1: net.minecraftforge.eventbus.EventBus$$Lambda$2506/1461637090@76bae3fb
		2: ASM: net.minecraftforge.common.ForgeInternalHandler@4707c812 playerLogin(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
		3: ASM: class com.supermartijn642.packedup.BackpackStorageManager onJoin(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
		4: ASM: class net.blay09.mods.farmingforblockheads.registry.market.MarketRegistryLoader onLogin(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
		5: net.minecraftforge.eventbus.EventBus$$Lambda$2506/1461637090@75821e4b
		6: ASM: gigaherz.toolbelt.slot.BeltExtensionSlot$EventHandlers@1b5227d2 joinWorld(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
		7: ASM: mekanism.common.CommonPlayerTracker@7ad772f6 onPlayerLoginEvent(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
		8: ASM: mcjty.theoneprobe.ForgeEventHandlers@772fd097 onPlayerLoggedIn(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
java.lang.NoSuchMethodError: net.minecraft.tags.TagRegistry.func_232932_a_()V
	at tfar.extratags.api.ModTag.markReady(ModTag.java:27)
	at java.util.ArrayList.forEach(Unknown Source)
	at tfar.extratags.ExtraTags.onPlayerLogin(ExtraTags.java:49)
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:212)
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:204)
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258)
	at net.minecraftforge.fml.hooks.BasicEventHooks.firePlayerLoggedIn(BasicEventHooks.java:44)
	at net.minecraft.server.management.PlayerList.func_72355_a(PlayerList.java:227)
	at net.minecraft.network.login.ServerLoginNetHandler.func_147326_c(ServerLoginNetHandler.java:116)
	at net.minecraft.network.login.ServerLoginNetHandler.func_73660_a(ServerLoginNetHandler.java:63)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:222)
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:133)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:866)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:286)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:788)
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:643)
	at net.minecraft.server.MinecraftServer.lambda$func_240784_a_$0(MinecraftServer.java:230)
	at java.lang.Thread.run(Unknown Source)

[04Aug2020 00:02:46.096] [Server thread/ERROR] [net.minecraft.server.MinecraftServer/]: Encountered an unexpected exception
java.lang.NoSuchMethodError: net.minecraft.tags.TagRegistry.func_232932_a_()V
	at tfar.extratags.api.ModTag.markReady(ModTag.java:27) ~[?:2.1e]
	at java.util.ArrayList.forEach(Unknown Source) ~[?:1.8.0_251]
	at tfar.extratags.ExtraTags.onPlayerLogin(ExtraTags.java:49) ~[?:2.1e]
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:212) ~[eventbus-2.2.0-service.jar:?]
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:204) ~[eventbus-2.2.0-service.jar:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258) ~[eventbus-2.2.0-service.jar:?]
	at net.minecraftforge.fml.hooks.BasicEventHooks.firePlayerLoggedIn(BasicEventHooks.java:44) ~[?:?]
	at net.minecraft.server.management.PlayerList.func_72355_a(PlayerList.java:227) ~[?:?]
	at net.minecraft.network.login.ServerLoginNetHandler.func_147326_c(ServerLoginNetHandler.java:116) ~[?:?]
	at net.minecraft.network.login.ServerLoginNetHandler.func_73660_a(ServerLoginNetHandler.java:63) ~[?:?]
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:222) ~[?:?]
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:133) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:866) ~[?:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:286) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:788) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:643) ~[?:?]
	at net.minecraft.server.MinecraftServer.lambda$func_240784_a_$0(MinecraftServer.java:230) ~[?:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_251]

**Comment by Tfarcenim** [comment]
resolved by 2.1f
